'use client';

import { useState } from 'react';
import { pick } from '@/lib/i18n';

/**
 * The analogy plus two optional, key-less visual aids.
 *
 * Both media sources are free and need no account: the diagram is generated by
 * Pollinations from a prompt the model wrote, and the video is a YouTube search
 * embed. Neither is loaded until the learner asks for it, so the page stays
 * fast and the low-bandwidth constraint is respected.
 */
export function AnalogyCard({ journey, lang }: { journey: any; lang: any }) {
  const [show, setShow] = useState<'none' | 'image' | 'video'>('none');
  const analogy = pick(journey.analogy, lang);
  const lowBandwidth = journey.constraint === 'low_bandwidth' || journey.constraint === 'offline_first';

  if (!analogy && !journey.media?.imagePrompt) return null;

  const imgSrc = journey.media?.imagePrompt
    ? `https://image.pollinations.ai/prompt/${encodeURIComponent(journey.media.imagePrompt)}?width=880&height=520&nologo=true`
    : '';
  const videoSrc = journey.media?.videoSearchQuery
    ? `https://www.youtube.com/embed?listType=search&list=${encodeURIComponent(journey.media.videoSearchQuery)}`
    : '';

  return (
    <section className="panel p-5">
      <div className="flex flex-wrap items-start justify-between gap-4">
        <div className="min-w-0 flex-1">
          <p className="text-xs font-semibold uppercase tracking-wide text-accent-soft">Think of it like this</p>
          <p className={`mt-1.5 text-base leading-relaxed text-slate-200 ${lang === 'ur' ? 'urdu text-lg' : ''}`}>
            {analogy}
          </p>
        </div>

        {!lowBandwidth && (
          <div className="flex shrink-0 gap-2">
            {imgSrc && (
              <button
                className="btn-ghost text-xs"
                onClick={() => setShow((s) => (s === 'image' ? 'none' : 'image'))}
              >
                {show === 'image' ? 'Hide diagram' : 'Show a diagram'}
              </button>
            )}
            {videoSrc && (
              <button
                className="btn-ghost text-xs"
                onClick={() => setShow((s) => (s === 'video' ? 'none' : 'video'))}
              >
                {show === 'video' ? 'Hide video' : 'Watch 2 min'}
              </button>
            )}
          </div>
        )}
      </div>

      {show === 'image' && (
        <figure className="animate-riseFade mt-4">
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src={imgSrc}
            alt={`Illustrative diagram: ${journey.media.imagePrompt}`}
            className="w-full rounded-xl border border-white/10 bg-white"
            loading="lazy"
          />
          <figcaption className="mt-2 text-[11px] text-slate-500">
            Generated illustration — a visual aid, not a source. The facts you are assessed on come from{' '}
            {journey.sourceName}.
          </figcaption>
        </figure>
      )}

      {show === 'video' && (
        <div className="animate-riseFade mt-4 aspect-video w-full overflow-hidden rounded-xl border border-white/10">
          <iframe
            src={videoSrc}
            title="Explainer video search"
            className="h-full w-full"
            allow="accelerometer; encrypted-media; picture-in-picture"
            referrerPolicy="strict-origin-when-cross-origin"
            loading="lazy"
          />
        </div>
      )}

      {lowBandwidth && (
        <p className="mt-3 text-[11px] text-slate-500">
          Diagram and video are hidden under the {String(journey.constraint).replace(/_/g, ' ')} constraint.
        </p>
      )}
    </section>
  );
}
