'use client';

import { useState, useEffect } from 'react';
import { pick } from '@/lib/i18n';
import { SmartDiagram } from './SmartDiagram';

/**
 * The analogy plus two optional, key-less visual aids.
 *
 * Both media sources are free and need no account: the diagram is generated by
 * Pollinations from a prompt the model wrote, and the video is a YouTube search
 * embed. Neither is loaded until the learner asks for it, so the page stays
 * fast and the low-bandwidth constraint is respected.
 */
export function AnalogyCard({ journey, lang }: { journey: any; lang: any }) {
  const [show, setShow] = useState<'none' | 'image' | 'video'>('none');
  const analogy = pick(journey.analogy, lang);
  const lowBandwidth = journey.constraint === 'low_bandwidth' || journey.constraint === 'offline_first';

  if (!analogy && !journey.media?.imagePrompt) return null;

  const [videoId, setVideoId] = useState<string | null>(null);

  useEffect(() => {
    if (journey.media?.videoSearchQuery) {
      fetch(`/api/youtube?q=${encodeURIComponent(journey.media.videoSearchQuery)}`)
        .then((res) => res.json())
        .then((data) => {
          if (data.videoId) setVideoId(data.videoId);
        })
        .catch(console.error);
    }
  }, [journey.media?.videoSearchQuery]);

  const imgSrc = journey.media?.imagePrompt
    ? `https://image.pollinations.ai/prompt/${encodeURIComponent(journey.media.imagePrompt)}?width=880&height=520&nologo=true`
    : '';
  const videoSrc = videoId
    ? `https://www.youtube.com/embed/${videoId}`
    : '';

  return (
    <section className="panel p-5">
      <div className="flex flex-wrap items-start justify-between gap-4">
        <div className="min-w-0 flex-1">
          <p className="text-xs font-semibold uppercase tracking-wide text-accent-soft">Think of it like this</p>
          <p className={`mt-1.5 text-base leading-relaxed text-slate-200 ${lang === 'ur' ? 'urdu text-lg' : ''}`}>
            {analogy}
          </p>
        </div>

        {!lowBandwidth && (
          <div className="flex shrink-0 gap-2">
            {imgSrc && (
              <button
                className="btn-ghost text-xs"
                onClick={() => setShow((s) => (s === 'image' ? 'none' : 'image'))}
              >
                {show === 'image' ? 'Hide diagram' : 'Show a diagram'}
              </button>
            )}
            {videoSrc && (
              <button
                className="btn-ghost text-xs"
                onClick={() => setShow((s) => (s === 'video' ? 'none' : 'video'))}
              >
                {show === 'video' ? 'Hide video' : 'Watch 2 min'}
              </button>
            )}
          </div>
        )}
      </div>

      {show === 'image' && (
        <SmartDiagram 
          sessionId={journey.id}
          imagePrompt={journey.media?.imagePrompt}
          topicTitle={journey.topic}
        />
      )}

      {show === 'video' && (
        <div className="animate-riseFade mt-4 aspect-video w-full overflow-hidden rounded-xl border border-white/10">
          <iframe
            src={videoSrc}
            title="Explainer video search"
            className="h-full w-full"
            allow="accelerometer; encrypted-media; picture-in-picture"
            referrerPolicy="strict-origin-when-cross-origin"
            loading="lazy"
          />
        </div>
      )}

      {lowBandwidth && (
        <p className="mt-3 text-[11px] text-slate-500">
          Diagram and video are hidden under the {String(journey.constraint).replace(/_/g, ' ')} constraint.
        </p>
      )}
    </section>
  );
}
